
module.exports = {
    firstBook: '.grid_list>:nth-child(1)',
    secondBook: '.grid_list>:nth-child(2)',
    thirdBook: '.grid_list>:nth-child(3)',
    historyTextInDetailedPage: '//div[@class="breadcrumbs"]//ul/li[4]/a',
    historyText: "Պատմություն",
    filter:  '//div[@class="sorting_block"]',
    priceFilter: '//div[@class="inner show"]//li[3]',
    firstBookPrice: ".grid_list>:nth-child(1) .price",
    secondBookPrice: ".grid_list>:nth-child(2) .price",
    addToCard: "div.add_button #product-addtocart-button",
    confirmation: ".message-success > div",
    confirmationText: "\nԴուք ավելացրել եք The Picture of Dorian Gray CD ձեր զամբյուղին.",
    shoppingBag: "div.page-wrapper a.action_btn.icon_cart",
    bookTitle: ".item_name > .combo_link",
    order: "#top-cart-btn-checkout",
    checkOut: ".breadcrumbs > .custom_container > ul > :nth-child(2) > div",
    emptyBag: ".delete_btn",
    yesDelete: ".action-primary > span",
    emptyBagText: ".subtitle",
    open: '//li[@data-container="product-grid"][1]//div[@class="product_name"]/a',
    books: ".catalog_menu>:nth-child(2)",
    history: ".opened>.submenu_list:nth-child(2)>.level0>:nth-child(3)>.level1>:nth-child(2)>:nth-child(1)",
    search: ".search_block .search_inner #search",
    hovered: ".hovered",
    URLText: '/am/catalog/category/view/id/7488/',
    dropDownFilter: '.category_select>.dropdown>.dropdown-menu',
    dorianGrayText: '.page_title',
    dorianGrayURL: '/am/catalog/product/view/id/60670/category/2/',
    checkoutURL: 'am/checkout/',
    deletePopUpWindowText: '#modal-content-18 > div',
    deletePopUpWindow: '.modal-inner-wrap',
    shoppingBagOpened: '#minicart-content-wrapper'

}